package com.G5.model;
// Generated 14 mars 2022, 00:05:46 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alerte generated by hbm2java
 */
@Entity
@Table(name = "alerte", catalog = "bd_cite2")
public class Alerte implements java.io.Serializable {

	private Integer idAlerte;
	private int idEtu;

	public Alerte() {
	}

	public Alerte(int idEtu) {
		this.idEtu = idEtu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ALERTE", unique = true, nullable = false)
	public Integer getIdAlerte() {
		return this.idAlerte;
	}

	public void setIdAlerte(Integer idAlerte) {
		this.idAlerte = idAlerte;
	}

	@Column(name = "ID_ETU", nullable = false)
	public int getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(int idEtu) {
		this.idEtu = idEtu;
	}

}
