package com.G5.model;
// Generated 17 mars 2022, 15:44:51 by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "bd_cite3")
public class Commande implements java.io.Serializable {

	private Integer idCommande;
	private Etudiant etudiant;
	private Menu menu;
	private Date datecommande;
	private String platcmdi;
	private String platcsoir;

	public Commande() {
	}

	public Commande(Etudiant etudiant, Menu menu) {
		this.etudiant = etudiant;
		this.menu = menu;
	}

	public Commande(Etudiant etudiant, Menu menu, Date datecommande, String platcmdi, String platcsoir) {
		this.etudiant = etudiant;
		this.menu = menu;
		this.datecommande = datecommande;
		this.platcmdi = platcmdi;
		this.platcsoir = platcsoir;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_COMMANDE", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_ETU", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_MENU", nullable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATECOMMANDE", length = 10)
	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "PLATCMDI", length = 65535)
	public String getPlatcmdi() {
		return this.platcmdi;
	}

	public void setPlatcmdi(String platcmdi) {
		this.platcmdi = platcmdi;
	}

	@Column(name = "PLATCSOIR", length = 65535)
	public String getPlatcsoir() {
		return this.platcsoir;
	}

	public void setPlatcsoir(String platcsoir) {
		this.platcsoir = platcsoir;
	}

}
