package com.G5.model;
// Generated 21 mars 2022, 14:59:08 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "bd_cite3")
public class Etudiant implements java.io.Serializable {

	private Integer idEtu;
	private String nom;
	private String prenoms;
	private String numeroEtu;
	private String nomParnt;
	private String numeroParnt;
	private String emailParnt;
	private Set<Alerte> alertes = new HashSet<Alerte>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);
	private Set<Permission> permissions = new HashSet<Permission>(0);

	public Etudiant() {
	}

	public Etudiant(String nom, String prenoms, String numeroEtu, String nomParnt, String numeroParnt,
			String emailParnt, Set<Alerte> alertes, Set<Commande> commandes, Set<Permission> permissions) {
		this.nom = nom;
		this.prenoms = prenoms;
		this.numeroEtu = numeroEtu;
		this.nomParnt = nomParnt;
		this.numeroParnt = numeroParnt;
		this.emailParnt = emailParnt;
		this.alertes = alertes;
		this.commandes = commandes;
		this.permissions = permissions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ETU", unique = true, nullable = false)
	public Integer getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(Integer idEtu) {
		this.idEtu = idEtu;
	}

	@Column(name = "NOM", length = 65535)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOMS", length = 65535)
	public String getPrenoms() {
		return this.prenoms;
	}

	public void setPrenoms(String prenoms) {
		this.prenoms = prenoms;
	}

	@Column(name = "NUMERO_ETU", length = 10)
	public String getNumeroEtu() {
		return this.numeroEtu;
	}

	public void setNumeroEtu(String numeroEtu) {
		this.numeroEtu = numeroEtu;
	}

	@Column(name = "NOM_PARNT", length = 65535)
	public String getNomParnt() {
		return this.nomParnt;
	}

	public void setNomParnt(String nomParnt) {
		this.nomParnt = nomParnt;
	}

	@Column(name = "NUMERO_PARNT", length = 10)
	public String getNumeroParnt() {
		return this.numeroParnt;
	}

	public void setNumeroParnt(String numeroParnt) {
		this.numeroParnt = numeroParnt;
	}

	@Column(name = "EMAIL_PARNT", length = 65535)
	public String getEmailParnt() {
		return this.emailParnt;
	}

	public void setEmailParnt(String emailParnt) {
		this.emailParnt = emailParnt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Alerte> getAlertes() {
		return this.alertes;
	}

	public void setAlertes(Set<Alerte> alertes) {
		this.alertes = alertes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Permission> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

}
