package com.G5.model;
// Generated 14 mars 2022, 00:29:40 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "bd_cite2")
public class Etudiant implements java.io.Serializable {

	private Integer idEtu;
	private String nom;
	private String prenoms;
	private Integer numeroEtu;
	private String nomParnt;
	private Integer numeroParnt;
	private String emailParnt;

	public Etudiant() {
	}

	public Etudiant(String nom, String prenoms, Integer numeroEtu, String nomParnt, Integer numeroParnt,
			String emailParnt) {
		this.nom = nom;
		this.prenoms = prenoms;
		this.numeroEtu = numeroEtu;
		this.nomParnt = nomParnt;
		this.numeroParnt = numeroParnt;
		this.emailParnt = emailParnt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_ETU", unique = true, nullable = false)
	public Integer getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(Integer idEtu) {
		this.idEtu = idEtu;
	}

	@Column(name = "NOM", length = 65535)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOMS", length = 65535)
	public String getPrenoms() {
		return this.prenoms;
	}

	public void setPrenoms(String prenoms) {
		this.prenoms = prenoms;
	}

	@Column(name = "NUMERO_ETU")
	public Integer getNumeroEtu() {
		return this.numeroEtu;
	}

	public void setNumeroEtu(Integer numeroEtu) {
		this.numeroEtu = numeroEtu;
	}

	@Column(name = "NOM_PARNT", length = 65535)
	public String getNomParnt() {
		return this.nomParnt;
	}

	public void setNomParnt(String nomParnt) {
		this.nomParnt = nomParnt;
	}

	@Column(name = "NUMERO_PARNT")
	public Integer getNumeroParnt() {
		return this.numeroParnt;
	}

	public void setNumeroParnt(Integer numeroParnt) {
		this.numeroParnt = numeroParnt;
	}

	@Column(name = "EMAIL_PARNT", length = 65535)
	public String getEmailParnt() {
		return this.emailParnt;
	}

	public void setEmailParnt(String emailParnt) {
		this.emailParnt = emailParnt;
	}

}
