package com.G5.model;
// Generated 18 mars 2022, 12:10:11 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permission generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "permission", catalog = "bd_cite3")
public class Permission implements java.io.Serializable {

	private Integer idPermission;
	private Etudiant etudiant;
	private String motifSorti;
	private Date dateSorti;
	private Date heureArrive;

	public Permission() {
	}

	public Permission(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Permission(Etudiant etudiant, String motifSorti, Date dateSorti, Date heureArrive) {
		this.etudiant = etudiant;
		this.motifSorti = motifSorti;
		this.dateSorti = dateSorti;
		this.heureArrive = heureArrive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PERMISSION", unique = true, nullable = false)
	public Integer getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(Integer idPermission) {
		this.idPermission = idPermission;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_ETUPermu", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@Column(name = "MOTIF_SORTI", length = 65535)
	public String getMotifSorti() {
		return this.motifSorti;
	}

	public void setMotifSorti(String motifSorti) {
		this.motifSorti = motifSorti;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_SORTI", length = 19)
	public Date getDateSorti() {
		return this.dateSorti;
	}

	public void setDateSorti(Date dateSorti) {
		this.dateSorti = dateSorti;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "HEURE_ARRIVE", length = 19)
	public Date getHeureArrive() {
		return this.heureArrive;
	}

	public void setHeureArrive(Date heureArrive) {
		this.heureArrive = heureArrive;
	}

}
