package com.G5.model;
// Generated 14 mars 2022, 00:29:40 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", catalog = "bd_cite2")
public class Permission implements java.io.Serializable {

	private Integer idPermission;
	private int idEtu;
	private String motifSorti;
	private Date dateSorti;
	private Date heureSorti;
	private Date heureArrive;

	public Permission() {
	}

	public Permission(int idEtu) {
		this.idEtu = idEtu;
	}

	public Permission(int idEtu, String motifSorti, Date dateSorti, Date heureSorti, Date heureArrive) {
		this.idEtu = idEtu;
		this.motifSorti = motifSorti;
		this.dateSorti = dateSorti;
		this.heureSorti = heureSorti;
		this.heureArrive = heureArrive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PERMISSION", unique = true, nullable = false)
	public Integer getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(Integer idPermission) {
		this.idPermission = idPermission;
	}

	@Column(name = "ID_ETU", nullable = false)
	public int getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(int idEtu) {
		this.idEtu = idEtu;
	}

	@Column(name = "MOTIF_SORTI", length = 65535)
	public String getMotifSorti() {
		return this.motifSorti;
	}

	public void setMotifSorti(String motifSorti) {
		this.motifSorti = motifSorti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_SORTI", length = 10)
	public Date getDateSorti() {
		return this.dateSorti;
	}

	public void setDateSorti(Date dateSorti) {
		this.dateSorti = dateSorti;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HEURE_SORTI", length = 8)
	public Date getHeureSorti() {
		return this.heureSorti;
	}

	public void setHeureSorti(Date heureSorti) {
		this.heureSorti = heureSorti;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HEURE_ARRIVE", length = 8)
	public Date getHeureArrive() {
		return this.heureArrive;
	}

	public void setHeureArrive(Date heureArrive) {
		this.heureArrive = heureArrive;
	}

}
